on:
  workflow_dispatch:
    inputs:
      write:
        description: "Change to 'true' to create issues, leave as 'false' to preview output"
        default: "false"
        type: boolean

name: Bulk issue creator

jobs:
  bulk_issue_creator:
    runs-on: ubuntu-latest
    name: Bulk Issue Creator
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install bulk-issue-creator
        run: npm install -g bulk-issue-creator

      - name: Initialize bulk-issue-creator
        run: bulk-issue-creator init

      - name: Create bulk issues
        uses: benbalter/bulk-issue-creator@v2
        with:
          write: ${{ github.event.inputs.write }}
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
